### ISSUE TITLE
Build error due to `is_sorted` on nightly Rust

### ISSUE THREAD

**Issue by rsammelson** [ripytide/btree_monstrousity#1]
It looks like `is_sorted` has been stabilized (https://github.com/rust-lang/rust/pull/128279), and the methods in polyfill.rs are now problematic because they have the same name as the methods on the std iterator trait.

**Comment by ripytide** [comment]
I've fixed the error and published `v0.0.5` for `btree_monstrousity` and updated the dependencies and published `v0.9.2` for `nodit`.
